### PR TITLE
[Fixes #37] Remove gitter link from readme

### LINKED ISSUE #37: Remove "chat on gitter" badge from readme

### PR DESCRIPTION
**Pull request by Halix267**
fixes #37 

This patch removes the gitter link from readme

### CODE REVIEW

**Comment by Halix267** [comment]
@ADI10HERO .Plzz review it

**Review by ADI10HERO — CHANGES_REQUESTED** [review]
Please add in description which issue it is fixing (description's "fixes.." is from where github's workflow to close issues is triggered)

Also your title "Update Readme, please rename it to "Remove gitter link from readme"
Update readme doesn't really tell a lot about the update

Also please read this https://github.com/Auto-DL/DLMML/pull/43#issuecomment-712781710

Thanks,
Adi

**Comment by Halix267** [comment]
@Kuro . I have made the changes . Review it.

**Comment by Halix267** [comment]
@ADI10HERO . I have made the changes ,review it

**Comment by Halix267** [comment]
Also the above commits is of  issue 

#17 Add Proper formating and docstring .

Plzz review it @ADI10HERO .

**Pull request closed without merging**
